### ISSUE TITLE
Builds are failing on Jenkins 1.555

### ISSUE THREAD

**Issue by NiematojakTomasz** [barchart/barchart-jenkins-cascade-plugin#41]
```
java.io.IOException: java.lang.NoSuchFieldException: includedRegions
    at com.barchart.jenkins.cascade.PluginUtilities.changeField(PluginUtilities.java:105)
    at com.barchart.jenkins.cascade.LayoutLogic.processLayout(LayoutLogic.java:478)
    at com.barchart.jenkins.cascade.LayoutLogic.process(LayoutLogic.java:292)
    at com.barchart.jenkins.cascade.LayoutBuildWrapper$1.tearDown(LayoutBuildWrapper.java:222)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:862)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:585)
    at hudson.model.Run.execute(Run.java:1676)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:519)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:231)
Caused by: java.lang.NoSuchFieldException: includedRegions
    at java.lang.Class.getDeclaredField(Class.java:1938)
    at com.barchart.jenkins.cascade.PluginUtilities.changeField(PluginUtilities.java:98)
    ... 9 more
```

It's clearly a dirty hack. Wouldn't be better to validate project configuration, than hacking it in strange way.

**Comment by NiematojakTomasz** [comment]
Workaround I am using: https://github.com/NiematojakTomsz/barchart-jenkins-cascade-plugin/tree/workaround-41 (anyway I wanted to configure all modules manuallly)

**Comment by mvberg** [comment]
It's not the Jenkins version, but rather the version of the Jenkins Git plugin: https://github.com/jenkinsci/git-plugin

I have committed a fix and tested on version 2.2.1

Last compatible version before this would be 1.6.0-beta (last 1.x release)

**Comment by lebrame** [comment]
Hello, 

I encountered the same issue but I don't know how to fix it !!
I need some advices please.

Thank you

Using Jenkins 1.596, Cascade Release Plugin 1.3.2, Maven 3.2.5 & Git plugin 2.3.5

**Comment by mvberg** [comment]
@lebrame Are you able to test the current head of the master branch? I
believe this fixes the issue.

If you can confirm, I'll release it.

**Comment by lebrame** [comment]
@mvberg 

Ok thank you very much for your responsivness.

I'll test it and give you the result !

**Comment by lebrame** [comment]
@mvberg 

Hi,

I already compile and test the plugin. The Build works well but the fact is I encounterd a new issue 

[CASCADE] Layout action: /action=create
[CASCADE] Layout project: Bcommon_build_(1_0)
[CASCADE] Project identity: /role=layout/family=28c5398c-3a1d-4210-a4e9-115eee5a34c5/project=b3486385-b3c9-4e7c-8e80-95d814366728
channel stopped
[CASCADE]   Project view: http://localhost:8082/jenkins/view/cascade/
[CASCADE]   Update SCM settings.
[CASCADE]   Use custom checkout strategy.
[CASCADE] 
[CASCADE] Layout project: Bcommon_build_(1_0)
[CASCADE] Cascade project: Bcommon_build_(1_0)_CASCADE
[CASCADE]   Creating cascade project.
[CASCADE]   Project identity: /role=cascade/family=28c5398c-3a1d-4210-a4e9-115eee5a34c5/project=1f8dd25d-7b18-4be1-bae3-f66f81cfbd8b
[CASCADE]   Provide description.
[CASCADE]   Persist project.
[CASCADE]   Project view: http://localhost:8082/jenkins/view/cascade/
[CASCADE]   Project created.
[CASCADE] 
[CASCADE] Module name: lu.tmp.build:Bcommon_1_0
[CASCADE] Member project: Bcommon_1_0_MEMBER
[CASCADE]   This is a layout module project, managed by user, skip.
[CASCADE] 
[CASCADE] Module name: lu.ept:common-interfaces
[CASCADE] Member project: common-interfaces_MEMBER
[CASCADE]   Creating project: common-interfaces_MEMBER
[CASCADE]   Clone config from layout into member.
[CASCADE]   Remove layout identity from the member.
[CASCADE]   Update member SCM settings.
[CASCADE]   Update member maven setting.
[CASCADE]   Member is sharing workspace with layout.
[CASCADE]   Configure member build wrappers.
[CASCADE]   Ensure member project identity.
FATAL: org/apache/maven/shared/release/versions/VersionInfo
java.lang.NoClassDefFoundError: org/apache/maven/shared/release/versions/VersionInfo
    at com.barchart.jenkins.cascade.MemberActionFactory.createFor(MemberActionFactory.java:55)
    at hudson.model.AbstractProject.createTransientActions(AbstractProject.java:756)
    at hudson.maven.AbstractMavenProject.createTransientActions(AbstractMavenProject.java:179)
    at hudson.maven.MavenModuleSet.createTransientActions(MavenModuleSet.java:465)
    at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:745)
    at hudson.maven.MavenModuleSet.updateTransientActions(MavenModuleSet.java:461)
    at hudson.model.AbstractProject.save(AbstractProject.java:304)
    at hudson.model.Job.addProperty(Job.java:510)
    at hudson.model.AbstractProject.addProperty(AbstractProject.java:775)
    at com.barchart.jenkins.cascade.PluginUtilities.ensureProperty(PluginUtilities.java:179)
    at com.barchart.jenkins.cascade.ProjectIdentity.ensureMemberIdentity(ProjectIdentity.java:214)
    at com.barchart.jenkins.cascade.LayoutLogic.processMemberUpdate(LayoutLogic.java:753)
    at com.barchart.jenkins.cascade.LayoutLogic.processMemberListCreate(LayoutLogic.java:555)
    at com.barchart.jenkins.cascade.LayoutLogic.processMemberList(LayoutLogic.java:498)
    at com.barchart.jenkins.cascade.LayoutLogic.process(LayoutLogic.java:275)
    at com.barchart.jenkins.cascade.LayoutBuildWrapper$1.tearDown(LayoutBuildWrapper.java:222)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:878)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
    at hudson.model.Run.execute(Run.java:1718)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.shared.release.versions.VersionInfo
    at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1375)
    at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1325)
    at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1078)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 22 more

Furthermore, I don't really understand why the plugin is creating new jobs in jenkins named with _MEMBER or _CASCADE !! What are they created for ?

Am I doing something wrong ? Did I miss sommething?

Thank you

 Using Jenkins 1.596, Cascade Release Plugin 1.3.2, Maven 3.2.5 & Git
 plugin 2.3.5

EDIT : Problem solved I had to update the maven-release-plugin !!! And now it works weel ;)

THANK YOU

**Comment by migger** [comment]
I can confirm that 1.3.3-SNAPSHOT on top of the master have no this issue.
